
import Head from 'next/head'
// import React from 'react';

function about(props) {
    return (
        <div>
            <Head>
                <title>about Create Next App</title>
                <meta name="description" content="Generated by about create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            gfdgdfgdfgfdgfdgfdgdfgfdgfdgdfgdfgg
        </div>
    );
}

export default about;